global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'REDIS_EXPORTER'
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - "redis_exporter:9121"
